create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), listing_id number(19,0), user_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table appUser (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references appUser;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references appUser;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references appUser;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references appUser;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references appUser;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), listing_id number(19,0), user_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table appUser (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references appUser;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references appUser;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references appUser;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references appUser;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references appUser;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), listing_id number(19,0), user_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table appUser (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references appUser;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references appUser;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references appUser;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references appUser;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references appUser;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), user_id number(19,0), listing_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table user (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references user;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references user;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references user;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), user_id number(19,0), listing_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table user (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references user;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references user;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references user;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), user_id number(19,0), listing_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table user (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references user;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references user;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references user;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
create table bid (id number(19,0) generated as identity, offer number(10,0), bidder_id number(19,0) not null, listing_id number(19,0) not null, primary key (id));
create table JPAUDIT (id number(19,0) generated as identity, action varchar2(255 char), date timestamp(6), origin_point varchar2(255 char), primary key (id));
create table listing (id number(19,0) generated as identity, asking_price number(10,0), currency number(5,0), end_date timestamp(6), is_available number(1,0), rating float(53), sold_price number(10,0), start_date timestamp(6), agent_id number(19,0) not null, property_id number(19,0) not null, primary key (id));
create table property (id number(19,0) generated as identity, address varchar2(255 char), owner_id number(19,0) not null, primary key (id));
create table review (id number(19,0) generated as identity, content varchar2(255 char), date_posted timestamp(6), user_id number(19,0), listing_id number(19,0), primary key (id));
create table role (id number(19,0) generated as identity, role_name varchar2(255 char), primary key (id));
create table user (id number(19,0) generated as identity, age varchar2(255 char), email varchar2(255 char), first_name varchar2(255 char), last_name varchar2(255 char), phone_number varchar2(255 char), primary key (id));
create table user_role (user_id number(19,0) not null, role_id number(19,0) not null, primary key (user_id, role_id));
alter table bid add constraint FKlv3wvxwx62go8g98owtwcbf7k foreign key (bidder_id) references user;
alter table bid add constraint FKi7c1ovio6hebeavj9jfbxhohn foreign key (listing_id) references listing;
alter table listing add constraint FKpn94bi06p8gowsvwdbyb4ethp foreign key (agent_id) references user;
alter table listing add constraint FKhesynelniju7efs7i9hh7nqm7 foreign key (property_id) references property;
alter table property add constraint FKjrxgmdv6y6703yh1o9mjo9lx9 foreign key (owner_id) references user;
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user;
alter table review add constraint FKtrw4aj9s48xdyu198mco3ngwg foreign key (listing_id) references listing;
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role;
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user;
